openapi: 3.0.0
info:
  title: CiCy Agent API
  version: 1.0.0


security:
  - BearerAuth: []

paths:
  /agentAppInfo:
    get:
      summary: agentAppInfo
      responses:
        '200':
          description: agentAppInfo response
          content:
            application/json:
  /clashConfig.yaml:
    get:
      summary: Clash Config
      responses:
        '200':
          description: Clash Config response
          content:
            text/plain:

  /file:
    get:
      summary: file
      parameters:
        - name: path
          in: query
          description: path
          required: true
      responses:
        '200':
          description: response
          content:
            application/octet-stream:
  /api:
    get:
      summary: api
      parameters:
        - name: method
          in: query
          description: The method to call
          required: true
          schema:
            type: string
            enum:
              - agentAppInfo
              - deviceInfo
              - isClashRunning
              - startClash
              - stopClash
              - updateClash
              - getClashConfig
              - onStartRecording
              - onStopRecording
              - onStartInput
              - onStopInput
              - screenWithXml
              - getInstalledApps
            default: agentAppInfo
      responses:
        '200':
          description: agentAppInfo response
          content:
            application/json:
  /jsonrpc:
    post:
      summary: json rpc
      description: |
        
        ### pressKey:

        ```json
        {
          "method": "pressKey",
          "params":["recent"]
        }
        ```
        ### editClashProxyConfig:

        ```json
        {
          "method": "editClashProxyConfig",
          "params":["192.168.124.244","4445","Account_10000","pwd"]
        }
        ```
        
        ### showToast:

        ```json
        {
          "method": "showToast",
          "params":["Test Toast Message"]
        }
        ```
        
        ### checkPermission:

        ```json
        {
          "method": "checkPermission",
          "params":["android.permission.POST_NOTIFICATIONS"]
        }
        ```
        ### requestPermission:

        ```json
        {
          "method": "requestPermission",
          "params":["android.permission.POST_NOTIFICATIONS"]
        }
        ```
        ### startAction:

        ```json
        {
          "method": "startAction",
          "params":["android.settings.APPLICATION_DETAILS_SETTINGS"]
        }
        ```
        ### setClashAutoRestart:

        ```json
        {
          "method": "setClashAutoRestart",
          "params":[false]
        }
        ```
        
        ### setAccessControlMode:

        ```json
        {
          "method": "setAccessControlMode",
          "params":["AcceptAll"]
        }
        ```
        
        
        ### setAccessControlPackages:

        ```json
        {
          "method": "setAccessControlPackages",
          "params":[["org.telegram.messenger.web"]]
        }
        ```
        
        ### shell:

        ```json
        {
          "method": "shell",
          "params":["pwd"]
        }
        ```
        
        ### readFile:

        ```json
        {
          "method": "readFile",
          "params":["/data/local/tmp/daemon.pid"]
        }
        ```
        
        ### writeFile:

        ```json
        {
          "method": "writeFile",
          "params":["/data/local/tmp/test.txt","text"]
        }
        ```
      

      tags:
        - jsonrpc
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JsonRpcRequest'
      responses:
        '200':
          description: BaseResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '404':
          description: Client not found
        '500':
          description: Internal server error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # Optional, can remove if not using JWT
      description: "Simple token authentication (just 'Bearer your-token')"
  schemas:
    BaseResponse:
      type: object
      properties:
        err:
          type: string
        result:
          type: object
    actionRequest:
      type: object
      required:
        - method
      properties:
        method:
          type: string

    JsonRpcRequest:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
        params:
          type: array
          items:
            type: string